<?php

namespace BriefcaseBundle\Repository;

/**
 * CourtCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtCaseRepository extends \Doctrine\ORM\EntityRepository
{

}
